[build]
  command = "npm ci && npm install --save-dev typescript@5.0.4 @types/react@18.0.38 @types/react-dom@18.0.11 && node setup-typescript.js && node netlify.js && npm run build"
  publish = ".next"
  functions = "netlify/functions"
  
# Ativa o deploy automático e configurações de cache
[build.processing]
  skip_processing = false

[build.environment]
  NODE_ENV = "production"
  USE_LOCAL_DB = "true"
  # Configuração específica para Typescript e Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [".env", "netlify/functions/local_coupons.json"]

# Plugin do Next.js com configurações simplificadas
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[context.production.environment]
  NODE_ENV = "production"
  USE_LOCAL_DB = "true"

[dev]
  functions = "netlify/functions"
  publish = ".next"
  framework = "#auto"
  autoLaunch = true 